/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'shift' : IDL.Text,
  'vendorId' : IDL.Text,
  'parentsName' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'department' : IDL.Text,
  'designation' : IDL.Text,
  'joiningDate' : IDL.Text,
  'photo' : IDL.Text,
});
export const Vendor = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'gstNumber' : IDL.Text,
  'contactPersonName' : IDL.Text,
  'contactNumber' : IDL.Text,
  'address' : IDL.Text,
});
export const AppUser = IDL.Record({
  'id' : IDL.Text,
  'permissions' : IDL.Text,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'role' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Attendance = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'employeeId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalEmployees' : IDL.Nat,
  'vendorDistribution' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'presentCount' : IDL.Nat,
  'shiftDistribution' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'attendancePercentage' : IDL.Float64,
  'absentCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmployee' : IDL.Func([Employee], [IDL.Text], []),
  'addVendor' : IDL.Func([Vendor], [IDL.Text], []),
  'appLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(AppUser)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeAppPassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'countEmployeesByVendor' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'createAppUser' : IDL.Func([IDL.Text, IDL.Text, AppUser], [IDL.Text], []),
  'deleteAppUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteEmployee' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteVendor' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllAppUsers' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(AppUser)],
      ['query'],
    ),
  'getAllAttendance' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getAttendanceByEmployee' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([IDL.Text], [DashboardStats], ['query']),
  'getEmployee' : IDL.Func([IDL.Text], [Employee], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendor' : IDL.Func([IDL.Text], [Vendor], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([Attendance], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAppUser' : IDL.Func([IDL.Text, IDL.Text, AppUser], [IDL.Text], []),
  'updateAttendance' : IDL.Func([Attendance], [IDL.Text], []),
  'updateEmployee' : IDL.Func([Employee], [IDL.Text], []),
  'updateVendor' : IDL.Func([Vendor], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'shift' : IDL.Text,
    'vendorId' : IDL.Text,
    'parentsName' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'department' : IDL.Text,
    'designation' : IDL.Text,
    'joiningDate' : IDL.Text,
    'photo' : IDL.Text,
  });
  const Vendor = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'gstNumber' : IDL.Text,
    'contactPersonName' : IDL.Text,
    'contactNumber' : IDL.Text,
    'address' : IDL.Text,
  });
  const AppUser = IDL.Record({
    'id' : IDL.Text,
    'permissions' : IDL.Text,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'role' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Attendance = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'employeeId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalEmployees' : IDL.Nat,
    'vendorDistribution' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'presentCount' : IDL.Nat,
    'shiftDistribution' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'attendancePercentage' : IDL.Float64,
    'absentCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmployee' : IDL.Func([Employee], [IDL.Text], []),
    'addVendor' : IDL.Func([Vendor], [IDL.Text], []),
    'appLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(AppUser)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeAppPassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'countEmployeesByVendor' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'createAppUser' : IDL.Func([IDL.Text, IDL.Text, AppUser], [IDL.Text], []),
    'deleteAppUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteEmployee' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteVendor' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllAppUsers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(AppUser)],
        ['query'],
      ),
    'getAllAttendance' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getAttendanceByEmployee' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([IDL.Text], [DashboardStats], ['query']),
    'getEmployee' : IDL.Func([IDL.Text], [Employee], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendor' : IDL.Func([IDL.Text], [Vendor], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([Attendance], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAppUser' : IDL.Func([IDL.Text, IDL.Text, AppUser], [IDL.Text], []),
    'updateAttendance' : IDL.Func([Attendance], [IDL.Text], []),
    'updateEmployee' : IDL.Func([Employee], [IDL.Text], []),
    'updateVendor' : IDL.Func([Vendor], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };